spring:
  test:
    database:
      replace: none  # Spring Boot가 H2 등으로 대체하지 않게 막기

  datasource:
    driver-class-name: org.postgresql.Driver
    username: testuser
    password: testpw
    url: jdbc:postgresql://localhost:5432/testdb  # 나중에 Testcontainers에서 override 됨

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop  # 테스트에서는 매번 새로 만듦
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      port: 27017  # flapdoodle가 자동으로 이 포트에 띄움
      database: testdb
    redis:
      host: redis
      port: 6379
    elasticsearch:
      uri: 192.168.0.17:30920
  task:
    scheduling:
      pool:
        size: 5
  batch:
    jdbc:
      initialize-schema: always  # 배치 메타 테이블 자동 생성
    job:
      enabled: false
  kafka:
    bootstrap-servers: 192.168.0.17:30092
    admin:
      auto-create: true
      #producer:
      #transactional-id-prefix: tx-mono- #트랜잭션 ID prefix
    consumer:
      enable-auto-commit: false  # 오토 커밋 금지
      auto-offset-reset: earliest
    listener:
      ack-mode: MANUAL  # 수동 ack
  scheduling:
    enabled: false

ELASTIC_SEARCH:
  IP: 192.168.0.17:9200

TIMEZONE:
  OFFSET: 9

search:
  service:
    url: localhost:8080

kafka:
  aggregateType:
    user: "user"
    post: "post"
    board: "board"
    school: "school"

  topic:
    user:
      create: "user-create-event"
      update: "user-update-event"
      delete: "user-delete-event"
    post:
      create: "post-create-event"
      update: "post-update-event"
      delete: "post-delete-event"
    board:
      create: "board-create-event"
      update: "board-update-event"
      delete: "board-delete-event"
    school:
      create: "school-create-event"
      update: "school-update-event"
      delete: "school-delete-event"

  groupId:
    board: "board-group-test"
    school: "school-group-test"
    search: "search-group-test"
